export const endpoints = {
  words: '/api/words',
  dailyWords: '/api/words/daily',
  learningSubmit: '/api/learning/submit',
  progress: '/api/progress',
  llmRateDifficulty: '/api/llm/rate-difficulty',
  sentencePrompts: '/api/sentences/prompts',
  sentenceRate: '/api/sentences/rate',
  freeExpressionRate: '/api/free-expression/rate',
  spellingQueue: '/api/spelling/queue',
  spellingSubmit: '/api/spelling/submit',
  logSummary: '/api/logs/summary',
  recentLogs: '/api/logs/recent',
  articles: '/api/articles',
  articleDetail: (id: string) => `/api/articles/${id}`,
  articleReadingStart: (id: string) => `/api/articles/${id}/reading/start`,
  articleVocabExtract: (id: string) => `/api/articles/${id}/vocab-extract`,
  articleVocab: (id: string) => `/api/articles/${id}/vocab`,
  articleLookup: (id: string) => `/api/articles/${id}/lookup`,
  articleComments: (id: string) => `/api/articles/${id}/comments`,
  readingLogFinish: (logId: string) => `/api/reading-logs/${logId}/finish`,
  readingLogLookup: (logId: string) => `/api/reading-logs/${logId}/lookup`,
  readingAgent: '/api/reading/agent',
  assessmentStart: '/api/assessment/initial/start',
  assessmentStep: (id: string, step: number) => `/api/assessment/${id}/step/${step}`,
  assessmentSubmit: (id: string, step: number) => `/api/assessment/${id}/step/${step}`,
  assessmentComplete: (id: string) => `/api/assessment/${id}/complete`,
  challengeStart: '/api/challenge/start',
  challengeSubmit: '/api/challenge/submit',
  challengeRecent: '/api/challenge/recent',
  levelDashboard: '/api/level/dashboard',
  levelHistory: '/api/level/history',
} as const
