export const endpoints = {
  authRegister: '/api/auth/register',
  authLogin: '/api/auth/login',
  authMe: '/api/auth/me',
  profile: '/api/profile',
  profileScores: '/api/profile/scores',
  profileScoresHistory: '/api/profile/scores/history',
  readingLookup: '/api/reading/lookup',
  evaluationLatest: '/api/evaluation/latest',
  feedback: '/api/feedback',
  profileLlm: '/api/profile/llm',
  llmPresets: '/api/profile/llm/presets',
  words: '/api/words',
  dailyWords: '/api/words/daily',
  learningSubmit: '/api/learning/submit',
  progress: '/api/progress',
  llmRateDifficulty: '/api/llm/rate-difficulty',
  sentencePrompts: '/api/sentences/prompts',
  sentenceRate: '/api/sentences/rate',
  freeExpressionRate: '/api/free-expression/rate',
  spellingQueue: '/api/spelling/queue',
  spellingSubmit: '/api/spelling/submit',
  logSummary: '/api/logs/summary',
  recentLogs: '/api/logs/recent',
  articles: '/api/articles',
  articlesRecommended: '/api/articles/recommended',
  articleDetail: (id: string) => `/api/articles/${id}`,
  articleReadingStart: (id: string) => `/api/articles/${id}/reading/start`,
  articleVocabExtract: (id: string) => `/api/articles/${id}/vocab-extract`,
  articleVocab: (id: string) => `/api/articles/${id}/vocab`,
  articleLookup: (id: string) => `/api/articles/${id}/lookup`,
  articleComments: (id: string) => `/api/articles/${id}/comments`,
  readingLogFinish: (logId: string) => `/api/reading-logs/${logId}/finish`,
  readingLogLookup: (logId: string) => `/api/reading-logs/${logId}/lookup`,
  readingAgent: '/api/reading/agent',
  assessmentStart: '/api/assessment/initial/start',
  assessmentSkip: '/api/assessment/initial/skip',
  assessmentNextBlock: (id: string) => `/api/assessment/${id}/next-block`,
  assessmentSubmitBlock: (id: string, blockIndex: number) => `/api/assessment/${id}/blocks/${blockIndex}/submit`,
  challengeStart: '/api/challenge/start',
  challengeSubmit: '/api/challenge/submit',
  challengeRecent: '/api/challenge/recent',
  levelDashboard: '/api/level/dashboard',
  levelHistory: '/api/level/history',
} as const
