-- PostgreSQL 幂等补丁：补齐 Score 内核列/表（AddScoreKernelM1 在 PG 上无法直接 EF 迁移）
-- 适用于 Docker / 从 SQLite 切换后仅有 InitialCreate 的旧库

ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "CefrDisplay" character varying(8);
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "DifficultyBucket" character varying(32);
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "LegacyCefrJson" character varying(2000);
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "ReadingScore" integer;
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "SpellingScore" integer;
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "VocabularyScore" integer;
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "WritingScore" integer;
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "ScoresUpdatedAt" timestamp with time zone;
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "ScoreSchemaVersion" integer NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS "BackgroundJobs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "JobType" character varying(64) NOT NULL,
    "PayloadJson" character varying(16000) NOT NULL,
    "Status" character varying(16) NOT NULL,
    "IdempotencyKey" character varying(128) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone,
    "ErrorMessage" character varying(2000)
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_BackgroundJobs_IdempotencyKey" ON "BackgroundJobs" ("IdempotencyKey");
CREATE INDEX IF NOT EXISTS "IX_BackgroundJobs_Status_CreatedAt" ON "BackgroundJobs" ("Status", "CreatedAt");

CREATE TABLE IF NOT EXISTS "LearningEvents" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "EventType" character varying(64) NOT NULL,
    "PayloadJson" character varying(16000) NOT NULL,
    "OccurredAt" timestamp with time zone NOT NULL,
    "IdempotencyKey" character varying(128) NOT NULL,
    CONSTRAINT "FK_LearningEvents_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_LearningEvents_IdempotencyKey" ON "LearningEvents" ("IdempotencyKey");
CREATE INDEX IF NOT EXISTS "IX_LearningEvents_UserId_OccurredAt" ON "LearningEvents" ("UserId", "OccurredAt");

CREATE TABLE IF NOT EXISTS "ProfileScoreSnapshots" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "Date" date NOT NULL,
    "ScoresJson" character varying(2000) NOT NULL,
    CONSTRAINT "FK_ProfileScoreSnapshots_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProfileScoreSnapshots_UserId_Date" ON "ProfileScoreSnapshots" ("UserId", "Date");

CREATE TABLE IF NOT EXISTS "EvaluationReports" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "TriggerType" character varying(32) NOT NULL,
    "AssessmentId" uuid,
    "InputSnapshotJson" character varying(16000) NOT NULL,
    "InputSnapshotHash" character varying(64) NOT NULL,
    "ContentJson" character varying(16000) NOT NULL,
    "Status" character varying(16) NOT NULL,
    "IdempotencyKey" character varying(128) NOT NULL,
    "ModelProfileId" character varying(80) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_EvaluationReports_Assessments_AssessmentId" FOREIGN KEY ("AssessmentId") REFERENCES "Assessments" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_EvaluationReports_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_EvaluationReports_IdempotencyKey" ON "EvaluationReports" ("IdempotencyKey");
CREATE INDEX IF NOT EXISTS "IX_EvaluationReports_UserId_CreatedAt" ON "EvaluationReports" ("UserId", "CreatedAt");

CREATE TABLE IF NOT EXISTS "UserFeedbacks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "FeedbackType" character varying(32) NOT NULL,
    "TargetWord" character varying(80) NOT NULL,
    "ContextJson" character varying(4000),
    "Status" character varying(16) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_UserFeedbacks_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_UserFeedbacks_UserId_CreatedAt" ON "UserFeedbacks" ("UserId", "CreatedAt");

CREATE TABLE IF NOT EXISTS "UserWordExcludes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "WordLemma" character varying(80) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_UserWordExcludes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserWordExcludes_UserId_WordLemma" ON "UserWordExcludes" ("UserId", "WordLemma");

CREATE TABLE IF NOT EXISTS "ChallengeSessions" (
    "Id" uuid NOT NULL PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "PackJson" character varying(32000) NOT NULL,
    "ConfirmationChallenge" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_ChallengeSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_ChallengeSessions_UserId_CreatedAt" ON "ChallengeSessions" ("UserId", "CreatedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20260630154336_AddScoreKernelM1', '10.0.9'),
    ('20260630160631_AddChallengeSession', '10.0.9')
ON CONFLICT ("MigrationId") DO NOTHING;
