-- PostgreSQL 幂等补丁：补齐 Score 内核列/表（AddScoreKernelM1 在 PG 上无法直接 EF 迁移）
-- 适用于 Docker / 从 SQLite 切换后仅有 InitialCreate 的旧库

ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "CefrDisplay" character varying(8);
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "DifficultyBucket" character varying(32);
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "LegacyCefrJson" character varying(2000);
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "ReadingScore" integer;
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "SpellingScore" integer;
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "VocabularyScore" integer;
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "WritingScore" integer;
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "ScoresUpdatedAt" timestamp with time zone;
ALTER TABLE "UserProgress" ADD COLUMN IF NOT EXISTS "ScoreSchemaVersion" integer NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS "BackgroundJobs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "JobType" character varying(64) NOT NULL,
    "PayloadJson" character varying(16000) NOT NULL,
    "Status" character varying(16) NOT NULL,
    "IdempotencyKey" character varying(128) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone,
    "ErrorMessage" character varying(2000)
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_BackgroundJobs_IdempotencyKey" ON "BackgroundJobs" ("IdempotencyKey");
CREATE INDEX IF NOT EXISTS "IX_BackgroundJobs_Status_CreatedAt" ON "BackgroundJobs" ("Status", "CreatedAt");

CREATE TABLE IF NOT EXISTS "LearningEvents" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "EventType" character varying(64) NOT NULL,
    "PayloadJson" character varying(16000) NOT NULL,
    "OccurredAt" timestamp with time zone NOT NULL,
    "IdempotencyKey" character varying(128) NOT NULL,
    CONSTRAINT "FK_LearningEvents_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_LearningEvents_IdempotencyKey" ON "LearningEvents" ("IdempotencyKey");
CREATE INDEX IF NOT EXISTS "IX_LearningEvents_UserId_OccurredAt" ON "LearningEvents" ("UserId", "OccurredAt");

CREATE TABLE IF NOT EXISTS "ProfileScoreSnapshots" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "Date" date NOT NULL,
    "ScoresJson" character varying(2000) NOT NULL,
    CONSTRAINT "FK_ProfileScoreSnapshots_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProfileScoreSnapshots_UserId_Date" ON "ProfileScoreSnapshots" ("UserId", "Date");

CREATE TABLE IF NOT EXISTS "EvaluationReports" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "TriggerType" character varying(32) NOT NULL,
    "AssessmentId" uuid,
    "InputSnapshotJson" character varying(16000) NOT NULL,
    "InputSnapshotHash" character varying(64) NOT NULL,
    "ContentJson" character varying(16000) NOT NULL,
    "Status" character varying(16) NOT NULL,
    "IdempotencyKey" character varying(128) NOT NULL,
    "ModelProfileId" character varying(80) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_EvaluationReports_Assessments_AssessmentId" FOREIGN KEY ("AssessmentId") REFERENCES "Assessments" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_EvaluationReports_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_EvaluationReports_IdempotencyKey" ON "EvaluationReports" ("IdempotencyKey");
CREATE INDEX IF NOT EXISTS "IX_EvaluationReports_UserId_CreatedAt" ON "EvaluationReports" ("UserId", "CreatedAt");

CREATE TABLE IF NOT EXISTS "UserFeedbacks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "FeedbackType" character varying(32) NOT NULL,
    "TargetWord" character varying(80) NOT NULL,
    "ContextJson" character varying(4000),
    "Status" character varying(16) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_UserFeedbacks_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_UserFeedbacks_UserId_CreatedAt" ON "UserFeedbacks" ("UserId", "CreatedAt");

CREATE TABLE IF NOT EXISTS "UserWordExcludes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "WordLemma" character varying(80) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_UserWordExcludes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserWordExcludes_UserId_WordLemma" ON "UserWordExcludes" ("UserId", "WordLemma");

CREATE TABLE IF NOT EXISTS "ChallengeSessions" (
    "Id" uuid NOT NULL PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "PackJson" character varying(32000) NOT NULL,
    "ConfirmationChallenge" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_ChallengeSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_ChallengeSessions_UserId_CreatedAt" ON "ChallengeSessions" ("UserId", "CreatedAt");

-- WordDifficultyAnnotations: AddScoreKernelM1 新增列（EF 迁移含 SQLite ALTER，PG 上需幂等补齐）
ALTER TABLE "WordDifficultyAnnotations" ADD COLUMN IF NOT EXISTS "DimensionsJson" character varying(2000);
ALTER TABLE "WordDifficultyAnnotations" ADD COLUMN IF NOT EXISTS "IntrinsicScore" integer;
ALTER TABLE "WordDifficultyAnnotations" ADD COLUMN IF NOT EXISTS "IsCurrent" boolean NOT NULL DEFAULT false;
ALTER TABLE "WordDifficultyAnnotations" ADD COLUMN IF NOT EXISTS "PromptVersion" character varying(40);
ALTER TABLE "WordDifficultyAnnotations" ADD COLUMN IF NOT EXISTS "SchemaVersion" integer NOT NULL DEFAULT 0;
ALTER TABLE "WordDifficultyAnnotations" ADD COLUMN IF NOT EXISTS "SourcesJson" character varying(4000);
ALTER TABLE "WordDifficultyAnnotations" ADD COLUMN IF NOT EXISTS "Version" integer NOT NULL DEFAULT 0;

-- UserWordRelationships: AddScoreKernelM1 新增列
ALTER TABLE "UserWordRelationships" ADD COLUMN IF NOT EXISTS "EstimatedKnownRate" double precision NOT NULL DEFAULT 0;
ALTER TABLE "UserWordRelationships" ADD COLUMN IF NOT EXISTS "PersonalDifficulty" integer;
ALTER TABLE "UserWordRelationships" ADD COLUMN IF NOT EXISTS "PersonalUpdatedAt" timestamp with time zone;

-- ArticleVocabMappings: 音标与例句缓存
ALTER TABLE "ArticleVocabMappings" ADD COLUMN IF NOT EXISTS "Phonetics" character varying(64) NOT NULL DEFAULT '';
ALTER TABLE "ArticleVocabMappings" ADD COLUMN IF NOT EXISTS "ExamplesJson" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20260630154336_AddScoreKernelM1', '10.0.9'),
    ('20260630160631_AddChallengeSession', '10.0.9'),
    ('20260708161532_AddArticleVocabPhoneticsAndExamples', '10.0.9')
ON CONFLICT ("MigrationId") DO NOTHING;

-- T-002 场景标注（本轮不做 EF 迁移，删库重建 + 幂等补丁）：Words 场景标注列 + WordScenarios 关联表
ALTER TABLE "Words" ADD COLUMN IF NOT EXISTS "Utility" character varying(16);
ALTER TABLE "Words" ADD COLUMN IF NOT EXISTS "Role" character varying(32);
ALTER TABLE "Words" ADD COLUMN IF NOT EXISTS "ScenarioAnnotationVersion" integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS "WordScenarios" (
    "WordId" uuid NOT NULL,
    "ScenarioKey" character varying(40) NOT NULL,
    CONSTRAINT "PK_WordScenarios" PRIMARY KEY ("WordId", "ScenarioKey"),
    CONSTRAINT "FK_WordScenarios_Words_WordId" FOREIGN KEY ("WordId") REFERENCES "Words" ("Id") ON DELETE CASCADE
);

-- T-005 WeaknessProfile + Finding（本轮不做 EF 迁移，删库重建 + 幂等补丁，枚举存字符串）
CREATE TABLE IF NOT EXISTS "WeaknessProfiles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "AssessmentId" uuid,
    "ModelProfileId" character varying(80) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_WeaknessProfiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WeaknessProfiles_Assessments_AssessmentId" FOREIGN KEY ("AssessmentId") REFERENCES "Assessments" ("Id") ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_WeaknessProfiles_UserId_AssessmentId" ON "WeaknessProfiles" ("UserId", "AssessmentId");
CREATE INDEX IF NOT EXISTS "IX_WeaknessProfiles_UserId_CreatedAt" ON "WeaknessProfiles" ("UserId", "CreatedAt");

CREATE TABLE IF NOT EXISTS "ProfileFindings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProfileId" bigint NOT NULL,
    "Dimension" character varying(16) NOT NULL,
    "DimensionKey" character varying(40) NOT NULL,
    "Polarity" character varying(16) NOT NULL,
    "Statement" character varying(500) NOT NULL,
    "EvidenceJson" character varying(4000) NOT NULL,
    "Confidence" character varying(16) NOT NULL,
    "Verification" character varying(16) NOT NULL,
    "VerificationNote" character varying(500),
    CONSTRAINT "FK_ProfileFindings_WeaknessProfiles_ProfileId" FOREIGN KEY ("ProfileId") REFERENCES "WeaknessProfiles" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_ProfileFindings_ProfileId" ON "ProfileFindings" ("ProfileId");

-- T-006 LearningPlan（本轮不做 EF 迁移，删库重建 + 幂等补丁；内容明细存 ContentJson）
CREATE TABLE IF NOT EXISTS "LearningPlans" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "StartDate" date NOT NULL,
    "ContentJson" character varying(16000) NOT NULL,
    "ModelProfileId" character varying(80) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_LearningPlans_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_LearningPlans_UserId_StartDate" ON "LearningPlans" ("UserId", "StartDate");

-- T-007 BottleneckInsight（本轮不做 EF 迁移，删库重建 + 幂等补丁，枚举存字符串）
CREATE TABLE IF NOT EXISTS "BottleneckInsights" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "Nature" character varying(32) NOT NULL,
    "Signals" character varying(64) NOT NULL,
    "Statement" character varying(500) NOT NULL,
    "EvidenceJson" character varying(2000) NOT NULL,
    "ReplanTriggered" boolean NOT NULL,
    "ModelProfileId" character varying(80) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_BottleneckInsights_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_BottleneckInsights_UserId_CreatedAt" ON "BottleneckInsights" ("UserId", "CreatedAt");

-- T-013 僵尸任务回收（本轮不做 EF 迁移，幂等补丁）：Processing 开始时间 + 回收重试计数
ALTER TABLE "BackgroundJobs" ADD COLUMN IF NOT EXISTS "StartedAt" timestamp with time zone;
ALTER TABLE "BackgroundJobs" ADD COLUMN IF NOT EXISTS "RetryCount" integer NOT NULL DEFAULT 0;

-- T-014 词毕业四阶段生命周期（本轮不做 EF 迁移，幂等补丁，枚举存字符串）
ALTER TABLE "UserWordRelationships" ADD COLUMN IF NOT EXISTS "LifecycleStage" character varying(32) NOT NULL DEFAULT 'Recognized';
ALTER TABLE "UserWordRelationships" ADD COLUMN IF NOT EXISTS "StageUpdatedAt" timestamp with time zone;
ALTER TABLE "UserWordRelationships" ADD COLUMN IF NOT EXISTS "PromptedUseConfirmedAt" timestamp with time zone;
ALTER TABLE "UserWordRelationships" ADD COLUMN IF NOT EXISTS "GraduatedFreeExpressionLogId" uuid;
-- 存量映射：SM-2 已成熟（连续 Remembered >= 2）→ Recalled，掌握度按阶段派生回填
UPDATE "UserWordRelationships" SET "LifecycleStage" = 'Recalled' WHERE "LifecycleStage" = 'Recognized' AND "RepeatCount" >= 2;
UPDATE "UserWordRelationships" SET "MasteryScore" = 50 WHERE "LifecycleStage" = 'Recalled';
UPDATE "UserWordRelationships" SET "MasteryScore" = 25 WHERE "LifecycleStage" = 'Recognized';
